---
name: "jellyfin-plugin-opendouban"
guid: "7834517B-1A9A-4758-9DD3-73FE02C98AA3"
version: "1.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
nicename: "Open Douban"
description: "Douban Scrapper"
overview: >
  This plugin is another implementation based on [douban-openapi-server]
  without any `ApiKey` preset
category: "Metadata"
owner: "caryyu"
artifacts:
  - "Jellyfin.Plugin.OpenDouban.dll"
